In [7]:
# Импортируем библиотеку
import pandas as pd

In [8]:
# Загружаем данные в датафрейм
data = pd.read_csv('data_for_test_task.csv', sep=';')
data.head()

   DOCUMENT_ID  LINE_ID                                    COL            VAL
0            0        1                            ид_пациента              0
1            0        1       результат_иммунодиагностики_дата     27.05.2013
2            0        1  результат_иммунодиагностики_результат  положительная
3            0        2       результат_иммунодиагностики_дата     08.08.2014
4            0        2  результат_иммунодиагностики_результат  положительная

In [9]:
# Создаем результиирующий датафрейм 
df = data.pivot(index=['DOCUMENT_ID', 'LINE_ID'], columns='COL')
df = df['VAL'].reset_index()
df.columns.name = None
df.head()

,DOCUMENT_ID,LINE_ID,вид_вакцинации,вид_вакцинации_код,дата_запрета,ид_пациента,медицинский_запрет_на_вакцинацию,отказ_от_вакцинации,подробности_вакцинации_дата,подробности_вакцинации_кратность,результат_иммунодиагностики_дата,результат_иммунодиагностики_результат
0,0,1,Туберкулез,80,NaN,0,NaN,NaN,02.06.2012,V1,27.05.2013,положительная
1,0,2,Полиомиелит,68,NaN,NaN,NaN,NaN,11.12.2012,V1,08.08.2014,положительная
2,0,3,Полиомиелит,69,NaN,NaN,NaN,NaN,30.08.2013,V2,23.09.2015,отрицательная
3,0,4,Полиомиелит,70,NaN,NaN,NaN,NaN,13.05.2014,V3,11.02.2017,отрицательная
4,0,5,"Дифтерия, коклюш, столбняк",50,NaN,NaN,NaN,NaN,14.12.2012,V1,NaN,NaN

In [10]:
# Дополняем значениями столбец 'ид_пациента'
df['ид_пациента'] = df['DOCUMENT_ID']
df.head()

,DOCUMENT_ID,LINE_ID,вид_вакцинации,вид_вакцинации_код,дата_запрета,ид_пациента,медицинский_запрет_на_вакцинацию,отказ_от_вакцинации,подробности_вакцинации_дата,подробности_вакцинации_кратность,результат_иммунодиагностики_дата,результат_иммунодиагностики_результат
0,0,1,Туберкулез,80,NaN,0,NaN,NaN,02.06.2012,V1,27.05.2013,положительная
1,0,2,Полиомиелит,68,NaN,0,NaN,NaN,11.12.2012,V1,08.08.2014,положительная
2,0,3,Полиомиелит,69,NaN,0,NaN,NaN,30.08.2013,V2,23.09.2015,отрицательная
3,0,4,Полиомиелит,70,NaN,0,NaN,NaN,13.05.2014,V3,11.02.2017,отрицательная
4,0,5,"Дифтерия, коклюш, столбняк",50,NaN,0,NaN,NaN,14.12.2012,V1,NaN,NaN